import {Router} from 'express';
import fs from 'node:fs/promises';
import path from 'node:path';
import {config} from '../config.js';
import {create_rate_limiter} from '../lib/rate_limit.js';
import {async_handler} from '../lib/async_handler.js';

// Minimal offline HIBP pwned password check using local prefix files generated by
// PwnedPasswordsDownloader (k-anonymity: SHA-1 first 5 hex chars as filename).
// Client computes SHA-1 and sends prefix+suffix — server never sees the password.

async function check_pwned_by_hash(prefix: string, suffix: string): Promise<{pwned: boolean; count: number}> {
    const file_path = path.join(config.pwned_data_dir, `${prefix}.txt`);
    let content: string;
    try {
        content = await fs.readFile(file_path, 'utf8');
    } catch {
        return {pwned: false, count: 0};
    }
    const lines = content.split(/\r?\n/);
    for (const line of lines) {
        const [suf, cnt] = line.split(':');
        if (suf?.toUpperCase() === suffix) {
            const n = Number(cnt || 0);
            return {pwned: true, count: Number.isFinite(n) ? n : 1};
        }
    }
    return {pwned: false, count: 0};
}

export function pwned_router() {
    const r = Router();

    // Optional lazy fetch of missing/expired prefix files using the official HIBP range endpoint.
    async function maybe_fetch_prefix(prefix: string) {
        if (!config.pwned_lazy_fetch) return;
        const dir = config.pwned_data_dir;
        await fs.mkdir(dir, {recursive: true});
        const file_path = path.join(dir, `${prefix}.txt`);
        const ttl_ms = config.pwned_ttl_hours * 3600 * 1000;
        const now = Date.now();
        let need = true;
        try {
            const stat = await fs.stat(file_path);
            need = now - stat.mtimeMs > ttl_ms;
        } catch {
            // File does not exist — need fetch
        }
        if (!need) return;
        const res = await fetch(`https://api.pwnedpasswords.com/range/${prefix}`, {
            headers: {'Add-Padding': 'true'},
            signal: AbortSignal.timeout(5000),
        });
        if (!res.ok) return;
        const text = await res.text();
        await fs.writeFile(file_path, text, 'utf8');
    }

    const rate_limit = create_rate_limiter({window_ms: config.rate_limit_window_ms, max: config.rate_limit_max});

    r.post('/', rate_limit, async_handler(async (req, res) => {
        if (!config.enable_pwned) return res.status(403).json({error: 'Pwned check disabled'});
        const prefix = String(req.body?.prefix || '');
        const suffix = String(req.body?.suffix || '');
        if (!prefix || !suffix) return res.status(400).json({error: 'Missing prefix/suffix'});
        if (!/^[0-9A-F]{5}$/.test(prefix) || !/^[0-9A-F]{35}$/.test(suffix)) {
            return res.status(400).json({error: 'Invalid SHA-1 prefix/suffix format'});
        }
        try {
            if (config.pwned_lazy_fetch) {
                await maybe_fetch_prefix(prefix);
            }
            const result = await check_pwned_by_hash(prefix, suffix);
            return res.json(result);
        } catch (e) {
            console.error(`[error] Pwned check failed: ${e instanceof Error ? e.message : 'Unknown error'}`);
            return res.status(500).json({error: 'Check failed'});
        }
    }));
    return r;
}
